id: P295455FF
initial_creation_type: ocr
source_metadata:
  volumes:
    39c447158286486e8f337a761c5c6dc5:
      base_file: v105.txt
      image_group_id: I1PD95950
      title: རིགས་པའི་ཐིགས་པའི་དོན་བསྡུས་པ།
      total_pages: 910
      volume_number: 105
