id: D4577227B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-27T08:22:26+00:00'
last_modified: '2022-05-30T04:51:09.602834+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    b45c:
      image_group_id: I1PD95950
      title: རིགས་པའི་ཐིགས་པའི་དོན་བསྡུས་པ།
      total_pages: 910
      order: 105
      base_file: b45c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
